# Site settings
title: 'MAR 440 UNSPOKEN' # Your Title
tagline: 'Untitled Interactive Group Project' # A brief tagline for your site
sidebar_image: /images/Untitled-Cover.jpg

# Build settings
markdown: kramdown
highlighter: pygments
baseurl: /MAR440 # the subpath of your site, e.g. /blog/
